export const PLAYER_MOVE_INIT = 'PLAYER_MOVE_INIT';
export const PLAYER_MOVE_SHOW_CITIES = 'PLAYER_MOVE_SHOW_CITIES';
export const PLAYER_MOVE_TO_CITY = 'PLAYER_MOVE_TO_CITY';
export const PLAYER_MOVE_CANCEL = 'PLAYER_MOVE_CANCEL';

export const PLAYER_BUILD_STATION = 'PLAYER_BUILD_STATION';

export const PLAYER_TREAT_DISEASE = 'PLAYER_TREAT_DISEASE';
export const PLAYER_CURE_DISEASE = 'PLAYER_CURE_DISEASE';
export const ERADICATE_DISEASE = 'ERADICATE_DISEASE';

export const CARD_DISCARD_FROM_HAND = 'CARD_DISCARD_FROM_HAND';
export const CARD_DRAW_CARDS_INIT = 'CARD_DRAW_CARDS_INIT';
export const CARD_DRAW_CARDS_HANDLE = 'CARD_DRAW_CARDS_HANDLE';

export const VICTORY = 'VICTORY';
export const DEFEAT = 'DEFEAT';

export const ACTIONS = [PLAYER_MOVE_TO_CITY, PLAYER_BUILD_STATION, PLAYER_CURE_DISEASE, PLAYER_TREAT_DISEASE];
